// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransitAnalyticsAPI.Persistence;

#nullable disable

namespace TransitAnalyticsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317103126_AddGtfsRouteShapesAndStops")]
    partial class AddGtfsRouteShapesAndStops
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsImportRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_version");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_import_runs");

                    b.ToTable("gtfs_import_runs", (string)null);
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgencyId")
                        .HasColumnType("text")
                        .HasColumnName("agency_id");

                    b.Property<long>("ImportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_run_id");

                    b.Property<string>("RouteColor")
                        .HasColumnType("text")
                        .HasColumnName("route_color");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("RouteLongName")
                        .HasColumnType("text")
                        .HasColumnName("route_long_name");

                    b.Property<string>("RouteShortName")
                        .HasColumnType("text")
                        .HasColumnName("route_short_name");

                    b.Property<string>("RouteTextColor")
                        .HasColumnType("text")
                        .HasColumnName("route_text_color");

                    b.Property<int?>("RouteType")
                        .HasColumnType("integer")
                        .HasColumnName("route_type");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_routes");

                    b.HasIndex("ImportRunId")
                        .HasDatabaseName("ix_gtfs_routes_import_run_id");

                    b.ToTable("gtfs_routes", (string)null);
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsShapePoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("DistanceTraveled")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_traveled");

                    b.Property<long>("ImportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_run_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("ShapeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shape_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_shape_points");

                    b.HasIndex("ImportRunId")
                        .HasDatabaseName("ix_gtfs_shape_points_import_run_id");

                    b.ToTable("gtfs_shape_points", (string)null);
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsStop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ImportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_run_id");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("location_type");

                    b.Property<string>("ParentStation")
                        .HasColumnType("text")
                        .HasColumnName("parent_station");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("text")
                        .HasColumnName("platform_code");

                    b.Property<string>("StopCode")
                        .HasColumnType("text")
                        .HasColumnName("stop_code");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<double>("StopLat")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lat");

                    b.Property<double>("StopLon")
                        .HasColumnType("double precision")
                        .HasColumnName("stop_lon");

                    b.Property<string>("StopName")
                        .HasColumnType("text")
                        .HasColumnName("stop_name");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_stops");

                    b.HasIndex("ImportRunId")
                        .HasDatabaseName("ix_gtfs_stops_import_run_id");

                    b.ToTable("gtfs_stops", (string)null);
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsStopTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ImportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_run_id");

                    b.Property<double?>("ShapeDistTraveled")
                        .HasColumnType("double precision")
                        .HasColumnName("shape_dist_traveled");

                    b.Property<string>("StopHeadsign")
                        .HasColumnType("text")
                        .HasColumnName("stop_headsign");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_stop_times");

                    b.HasIndex("ImportRunId")
                        .HasDatabaseName("ix_gtfs_stop_times_import_run_id");

                    b.ToTable("gtfs_stop_times", (string)null);
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsTrip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("DirectionId")
                        .HasColumnType("integer")
                        .HasColumnName("direction_id");

                    b.Property<long>("ImportRunId")
                        .HasColumnType("bigint")
                        .HasColumnName("import_run_id");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<string>("ShapeId")
                        .HasColumnType("text")
                        .HasColumnName("shape_id");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("text")
                        .HasColumnName("trip_headsign");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_gtfs_trips");

                    b.HasIndex("ImportRunId")
                        .HasDatabaseName("ix_gtfs_trips_import_run_id");

                    b.ToTable("gtfs_trips", (string)null);
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.VehiclePosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bearing")
                        .HasColumnType("text")
                        .HasColumnName("bearing");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at_utc");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("SourceEntityId")
                        .HasColumnType("text")
                        .HasColumnName("source_entity_id");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_positions");

                    b.ToTable("vehicle_positions", (string)null);
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsRoute", b =>
                {
                    b.HasOne("TransitAnalyticsAPI.Models.Entities.GtfsImportRun", "ImportRun")
                        .WithMany("Routes")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gtfs_routes_gtfs_import_runs_import_run_id");

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsShapePoint", b =>
                {
                    b.HasOne("TransitAnalyticsAPI.Models.Entities.GtfsImportRun", "ImportRun")
                        .WithMany("ShapePoints")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gtfs_shape_points_gtfs_import_runs_import_run_id");

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsStop", b =>
                {
                    b.HasOne("TransitAnalyticsAPI.Models.Entities.GtfsImportRun", "ImportRun")
                        .WithMany("Stops")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gtfs_stops_gtfs_import_runs_import_run_id");

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsStopTime", b =>
                {
                    b.HasOne("TransitAnalyticsAPI.Models.Entities.GtfsImportRun", "ImportRun")
                        .WithMany("StopTimes")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gtfs_stop_times_gtfs_import_runs_import_run_id");

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsTrip", b =>
                {
                    b.HasOne("TransitAnalyticsAPI.Models.Entities.GtfsImportRun", "ImportRun")
                        .WithMany("Trips")
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gtfs_trips_gtfs_import_runs_import_run_id");

                    b.Navigation("ImportRun");
                });

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.GtfsImportRun", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("ShapePoints");

                    b.Navigation("StopTimes");

                    b.Navigation("Stops");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
