// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransitAnalyticsAPI.Persistence;

#nullable disable

namespace TransitAnalyticsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransitAnalyticsAPI.Models.Entities.VehiclePosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bearing")
                        .HasColumnType("text")
                        .HasColumnName("bearing");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at_utc");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at_utc");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("SourceEntityId")
                        .HasColumnType("text")
                        .HasColumnName("source_entity_id");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_positions");

                    b.ToTable("vehicle_positions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
